export const AUTH_START = "AUTH_START";
export const AUTH_END = "AUTH_END";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_SUCCESS = "AUTH_SUCCESS";

export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_END = "LOGOUT_END";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const FETCH_COUNTRIES_START = "FETCH_COUNTRIES_START";
export const FETCH_COUNTRIES_END = "FETCH_COUNTRIES_END";
export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS";
